---

- hosts: 'aws'
  remote_user: 'ubuntu'
  gather_facts: false
  roles:
    - nginx
    - mysql
    - wordpress
  tasks:

    # - name: 'Debug'
    #   become: true
    #   debug:
    #     msg: '{{ ansible_ssh_private_key_file }}'

    # - name: Change WP DB config
    #   become: true
    #   lineinfile:
    #     path: /var/www/wordpress/wp-config.php
    #     regexp: "^define( 'DB_NAME', 'database_name_here' );"
    #     line: "define( 'DB_NAME', 'wordpress_db' );"

    # - name: Change WP username config
    #   become: true
    #   lineinfile:
    #     path: /var/www/wordpress/wp-config.php
    #     regexp: "^define( 'DB_USER', 'username_here' );"
    #     line: "define( 'DB_USER', 'wordpress_user' );"

    # - name: Change WP user password config
    #   become: true
    #   lineinfile:
    #     path: /var/www/wordpress/wp-config.php
    #     regexp: "^define( 'DB_PASSWORD', 'password_here' );"
    #     line: "define( 'DB_PASSWORD', '12345' );"

    # - name: copy nginx config file
    #   copy: 
    #     src: /home/hrayr/epam-ansible/nginx.conf 
    #     dest: /etc/nginx/sites-available/wordpress
    #   become: true
